name: restaum
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  audioplayers: ^5.2.1
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/swords.png
    - assets/sounds/alert.wav
    - assets/sounds/bonus.wav
    - assets/sounds/tap.wav

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
